### ISSUE TITLE
all_selftests() outputs to stdout

### ISSUE THREAD

**Issue by draik** [freenas/py-SMART#17]
When calling dev.all_selftests(), the output is put into stdout, and cannot be assigned to variable, or put through format(). Suggesting to put print statement as return.

**Comment by draik** [comment]
Change "print(test)" to "return test"

https://github.com/freenas/py-SMART/blob/89ea65c7e756ad0c494e6397b26751cd43c9bcbf/pySMART/device.py#L374

**Comment by william-gr** [comment]
We have not been maintaining this library lately.
If you are able to submit a PR we will gladly review and merge it though.

**Comment by draik** [comment]
Sweet! PR done.

**Comment by ophilli** [comment]
It looks like this issue was fixed in PR #18 and PR #19 . Is it possible to close this issue now?

**Comment by draik** [comment]
Looks good to me. Close it.
